import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import NavBar from "@/components/NavBar";
import { Providers } from "./providers";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${onest.className} antialiased`}>
        <Providers>
          <Script
            src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_API_KEY}&libraries=places`}
            strategy="beforeInteractive"
          />
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
